site_name: Vertex-CLI Documentation
site_url: https://github.com/prtm2110/vertex-cli
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.tooltips
    - content.footnotes
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: amber
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: light blue

plugins:
  - social
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - CLI Tool Guide: cli_tool_docs.md
  - Contributors Guide: contributors_guide.md
  - API Reference: references.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Prtm2110
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pratham-hole

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list

copyright: |
  &copy; 2025 <a href="https://github.com/prtm2110" target="_blank" rel="noopener">Pratham Hole</a>
